services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Subugoe\Find\:
    resource: '../Classes/*'
    exclude: '../Classes/Ajax/EidSettings.php'

  Subugoe\Find\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true